version: "3.6"
services:
  chia_farm:
    container_name: chia-farm
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    networks:
      - chia_network
    ports:
      - 8444:8444
    environment:
      service: farmer-no-wallet
      keys: /root/.mnemonic
      TZ: "Asia/Jakarta"
      upnp: "true"
      log_level: INFO
      log_to_file: "true"
      CHIA_ROOT: /root/.chia/mainnet/
      healthcheck: "true"
      plots_dir: "/root/.chia/plots/01/:/root/.chia/plots/02/:/root/.chia/plots/03/:/root/.chia/plots/04/"
    volumes:
      - /root/.mnemonic:/root/.mnemonic
      - /root/.chia/mainnet/config/ssl/ca/:/root/.chia/mainnet/config/ssl/ca/
      - /root/.chia/mainnet/db/:/root/.chia/mainnet/db/
      - /root/.chia/mainnet/wallet/db/:/root/.chia/mainnet/wallet/db/
      - /root/.chia/plots/:/root/.chia/plots/

  chia_wallet:
    container_name: chia-wallet
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    network_mode: host
    environment:
      service: wallet
      keys:
      TZ: "Asia/Jakarta"
      upnp: "false"
      log_level: INFO
      log_to_file: "true"
      CHIA_ROOT: /root/.chia/mainnet/
      healthcheck: "true"
    volumes:
      - /root/.chia/lightnet/wallet/db/:/root/.chia/mainnet/wallet/db/

networks:
  chia_network:
    name: chia-network
    driver: bridge

