version: "3.6"
services:
  chia_farmer:
    container_name: chia-farmer
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:1.6.1
    networks:
      - chia_network
    ports:
      - 8444:8444
    environment:
      service: farmer-only
      keys: /root/.mnemonic
      TZ: "Asia/Jakarta"
      upnp: "true"
      log_level: INFO
      log_to_file: "true"
      CHIA_ROOT: /root/.chia/mainnet/
      healthcheck: "true"
    volumes:
      - /root/.mnemonic:/root/.mnemonic
      - /root/.chia/mainnet/config/ssl/ca/:/root/.chia/mainnet/config/ssl/ca/
      - /root/.chia/mainnet/db/:/root/.chia/mainnet/db/
      - /root/.chia/mainnet/wallet/db/:/root/.chia/mainnet/wallet/db/

  chia_harvester:
    container_name: chia-harvester
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:1.6.1
    networks:
      - chia_network
    environment:
      service: harvester
      keys:
      TZ: "Asia/Jakarta"
      log_level: INFO
      log_to_file: "true"
      CHIA_ROOT: /root/.chia/mainnet/
      healthcheck: "true"
      farmer_address: chia_farmer
      farmer_port: 8447
      ca: /root/.chia/mainnet/config/ssl/ca/
      plots_dir: "/root/.chia/plots/01/:/root/.chia/plots/02/:/root/.chia/plots/03/:/root/.chia/plots/04/"
    volumes:
      - /root/.chia/mainnet/config/ssl/ca/:/root/.chia/mainnet/config/ssl/ca/
      - /root/.chia/plots/:/root/.chia/plots/

networks:
  chia_network:
    name: chia-network
    driver: bridge

