version: "3.6"
services:
  chia-wallet:
    container_name: chia_wallet
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    networks:
      - chia_network
    environment:
      service: wallet
      keys:
      TZ: "Asia/Jakarta"
      upnp: "false"
      log_level: INFO
      log_to_file: "true"
      CHIA_ROOT: /root/.chia/mainnet/
      healthcheck: "true"
    volumes:
      - /root/.chia/lightnet/wallet/db/:/root/.chia/mainnet/wallet/db/
