version: "3.6"
services:
  chia_wallet:
    container_name: chia-wallet
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:1.6.1
    environment:
      service: wallet
      keys:
      TZ: "Asia/Jakarta"
      upnp: "false"
      log_level: INFO
      log_to_file: "true"
      CHIA_ROOT: /root/.chia/mainnet/
      healthcheck: "true"
      fullnode_address: chia_farmer
      fullnode_port: 8444
    volumes:
      - /root/.chia/lightnet/wallet/db/:/root/.chia/mainnet/wallet/db/

networks:
  chia_network:
    name: chia-network
    driver: bridge

